spring:
  datasource:
    url: jdbc:mysql://localhost:3306/joycourse?characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: joycourse
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

url:
  frontend: http://127.0.0.1:3000

oauth2:
  providers:
    naver:
      client-id: ${NAVER_CLIENT_ID}
      client-secret: ${NAVER_CLIENT_SECRET}
      redirect-uri: ${url.frontend}/accounts/naver/callback
      login-uri: https://nid.naver.com/oauth2.0/authorize
      token-uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me
      unlink-uri: https://oauth2.googleapis.com/revoke
      # login-uri: https://nid.naver.com/oauth2.0/authorize?response_type=code&client_id=%s&redirect_uri=%s
      # token-uri: https://nid.naver.com/oauth2.0/token
      # user-info-uri: https://openapi.naver.com/v1/nid/me
      # unlink-uri: https://nid.naver.com/oauth2.0/token
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect-uri: ${url.frontend}/accounts/google/callback
      login-uri: https://accounts.google.com/o/oauth2/v2/auth?scope=https://www.googleapis.com/auth/userinfo.email&access_type=offline&include_granted_scopes=true&response_type=code&client_id=%s&redirect_uri=%s
      token-uri: https://oauth2.googleapis.com/token
      user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
      unlink-uri: https://oauth2.googleapis.com/revoke
    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      client-secret:
      redirect-uri: ${url.frontend}/accounts/kakao/callback
      login-uri: https://kauth.kakao.com/oauth/authorize?response_type=code&client_id=%s&redirect_uri=%s
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me
      unlink-uri: https://kapi.kakao.com/v1/user/unlink

place-api:
  request-parameter:
    request-uri: https://dapi.kakao.com
    rest-api-key: ${KAKAO_API_KEY}