spring:
  redis:
    port: 6379
    host: 127.0.0.1  # 스프링 부트도 도커로 올리면 바꿔야함
  datasource:
    url: jdbc:mysql://localhost:3306/joycourse?characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: joycourse
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

auth:
  access-token-key: a7349a21d63950b9b02c6129839096d4
  refresh-token-key: 36260fc7b27bf642d9015c9820e260e2

file-dir:
  path: images
  download-url: http://127.0.0.1:8080/files
