server:
  port: 8080
  servlet:
    multipart:
      maxFileSize: 5MB
      maxRequestSize: 10MB

spring:
  profiles:
    active: ${PROFILE}
  mvc:
    throw-exception-if-no-handler-found: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/auth/callback/{registrationId}"
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/auth/callback/{registrationId}"
            client-name: naver
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/auth/callback/{registrationId}"
            client-name: kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

endpoint:
  authenticate:
    "[*]":
      - /accounts/**
      - /course/**
  non-authenticate:
    GET:
      - /course/
      - /course
  redirect:
    web: http://localhost:3000/callback
    web-failure: http://localhost:3000/callback/failure

cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

auth:
  access-token-key: this0is0just0sample0should0chang
  refresh-token-key: this0is0just0sample0should0chang
  access-token-cookie-name: actc
  refresh-token-cookie-name: rctc
  access-token-max-age: 1800
  refresh-token-max-age: 10800

place-api:
  request-parameter:
    request-uri: https://dapi.kakao.com
    rest-api-key: ${KAKAO_API_KEY}


