spring:
  profiles: # 이렇게 하면 커멘드창에 spring.profiles.active=dev 근데 이러면 dev도 읽으라고 알려주는거
    active: dev

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
