spring:
  redis:
    port: 6379
    host: ${REDIS_SERVER_ADD}  # 스프링 부트도 도커로 올리면 바꿔야함
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER_ADD}:3306/joycourse_mysql?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: joycourse
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

auth:
  access-token-key: a7349a21d63950b9b02c6129839096d4
  refresh-token-key: 36260fc7b27bf642d9015c9820e260e2

elasticsearch:
  host: ${ELASTICSEARCH_SERVER_ADD}
  port: 9200
  username: elastic
  password: joycourse

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: TRACE

file-dir:
  path: .\images
  download-url: http://${FILE_SERVER_ADD}/files/
