oauth2:
  user:
    naver:
      client-id: jvsPsVG49KGWif6nlZ6g
      client-secret: zPD8YV1Y23
      redirect-uri: http://127.0.0.1:3000/accounts/naver/callback


  provider:
    naver:
      token-uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me
